server:
  port: 5354
  address: 127.0.0.1
  timeout: 5000

# Cache configuration
cache:
  enabled: true
  maxSize: 10000
  ttl: 3600

# Upstream DNS servers
upstreams:
  groups:
    default:
      - 8.8.8.8
      - 1.1.1.1
      - https://dns.google/dns-query
    kids:
      - 1.1.1.3
      - 8.8.8.8
  timeout: 5000

  # Blocking configuration
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    malware:
      - https://raw.githubusercontent.com/blocklistproject/Lists/master/malware.txt
  allowlists:
    whitelist:
      - ./allowlists/whitelist.txt
  clientGroupsBlock:
    default:
      - ads
    kids:
      - ads
      - malware

# Logging configuration
logging:
  level: info
  queryLog: true
  file: ./logs/server.log
  format: json
